//#include "examples/Alpha-Blending-Cpu/Alpha-Blending-Cpu-example.cpp"
//#include "examples/Animated-Shapes/Animated-Shapes-example.cpp"
//#include "examples/Benchmark/Benchmark.cpp"
//#include "examples/Blocks/Blocks-example.cpp"
#include "examples/Bubble-Effect/Bubble-Effect-example.cpp"
//#include "examples/Buttons/Buttons-example.cpp"

//#include "examples/Clipping/Clipping-example.cpp"
//#include "examples/Clipping/clipping-item-factory.cpp"

//#include "examples/Clipping-Draw-Order/Clipping-Draw-Order.cpp"
//#include "examples/Compressed-Texture-Formats/Compressed-Texture-Formats-example.cpp"

//#include "examples/Contact-Cards/Contact-Cards-example.cpp"
//#include "examples/Contact-Cards/clipped-image.cpp"
//#include "examples/Contact-Cards/contact-card.cpp"
//#include "examples/Contact-Cards/contact-card-layouter.cpp"
//#include "examples/Contact-Cards/contact-data.cpp"

//#include "examples/compressed-texture-formats/compressed-texture-formats-example.cpp"

//#include "examples/Cube-Transition-Effect/Cube-Transition-Effect-example.cpp"
//#include "examples/Effects-View/Effects-View-example.cpp"
//#include "examples/Flex-Container/Flex-Container-example.cpp"
//#include "examples/Focus-Integration/Focus-Integration.cpp"


//#include "examples/Gradients/Gradients-example.cpp"
//#include "examples/Hello-World/Hello-World-example.cpp"
//#include "examples/Homescreen-Benchmark/Homescreen-Benchmark.cpp"
//#include "examples/Image-Scaling-And-Filtering/Image-Scaling-And-Filtering-example.cpp"
//#include "examples/Image-Scaling-Irregular-Grid/Image-Scaling-Irregular-Grid-example.cpp"
//#include "examples/Image-View/Image-View-example.cpp"
//#include "examples/Image-View-Alpha-Blending/Image-View-Alpha-Blending-example.cpp"
//#include "examples/Image-View-Pixel-Area/Image-View-Pixel-Area-example.cpp"
//#include "examples/Image-View-Svg/Image-View-Svg-example.cpp"
//#include "examples/Image-View-Url/Image-View-Url-example.cpp"
//#include "examples/Item-View/Item-View-example.cpp"
//#include "examples/Line-Mesh/Line-Mesh-example.cpp"
//#include "examples/Magnifier/Magnifier-example.cpp"
//#include "examples/Mesh-Morph/Mesh-Morph-example.cpp"
//#include "examples/Mesh-Visual/Mesh-Visual-example.cpp"
//#include "examples/Model3d-View/Model3d-View-example.cpp"
//#include "examples/Motion-Blur/Motion-Blur-example.cpp"
//#include "examples/Motion-Stretch/Motion-Stretch-example.cpp"
//#include "examples/Native-Image-Source/Native-Image-Source-example.cpp"
//#include "examples/Perf-Scroll/Perf-Scroll.cpp"
//#include "examples/Pivot/Pivot-example.cpp"
//#include "examples/Point-mesh/Point-mesh-example.cpp"
//#include "examples/Popup/Popup-example.cpp"
//#include "examples/Primitive-Shapes/Primitive-Shapes-example.cpp"
//#include "examples/Progress-Bar/Progress-Bar-example.cpp"
//#include "examples/Property-Notification/Property-Notification-example.cpp"
//#include "examples/Ray-Marching/Ray-Marching-example.cpp"
//#include "examples/refraction-effect/refraction-effect-example.cpp"
//#include "examples/Remote-Image-Loading/Remote-Image-Loading-example.cpp"
//#include "examples/Renderer-Stencil/Renderer-Stencil-example.cpp"
//#include "examples/Rendering-Basic-Light/Rendering-Basic-Light-example.cpp"

//#include "examples/Rendering-Basic-Pbr/Rendering-Basic-Pbr-example.cpp"
//#include "examples/Rendering-Basic-Pbr/ktx-loader.cpp"
//#include "examples/Rendering-Basic-Pbr/model-pbr.cpp"
//#include "examples/Rendering-Basic-Pbr/model-skybox.cpp"
//#include "examples/Rendering-Basic-Pbr/obj-loader.cpp"

//#include "examples/rendering-skybox/look-camera.cpp"
//#include "examples/rendering-skybox/rendering-skybox.cpp"

//#include "examples/Rendering-Cube/Rendering-Cube.cpp"
//#include "examples/Rendering-Line/Rendering-Line.cpp"

//#include "examples/Rendering-Textured-Cube/Rendering-Textured-Cube.cpp"
//#include "examples/Rendering-Triangle/Rendering-Triangle.cpp"
//#include "examples/Scroll-View/Scroll-View-example.cpp"
//#include "examples/Shadows-And-Lights/Shadows-And-Lights-example.cpp"
//#include "examples/Size-Negotiation/Size-Negotiation-example.cpp"

//#include "examples/simple-visuals-control/my-control.cpp"
//#include "examples/simple-visuals-control/my-control-impl.cpp"
//#include "examples/simple-visuals-control/simple-visuals-application.cpp"
//#include "examples/simple-visuals-control/simple-visuals-example.cpp"

//#include "examples/Sparkle/Sparkle-Effect-example.cpp"

//#include "examples/styling/Style-example.cpp"
//#include "examples/styling/image-channel-control.cpp"
//#include "examples/styling/image-channel-control-impl.cpp"
//#include "examples/styling/styling-application.cpp"

//#include "examples/Text-Editor/Text-Editor-example.cpp"

//#include "examples/text-fonts/text-fonts-example.cpp"

//#include "examples/text-label/expanding-buttons.cpp"
//#include "examples/text-label/expanding-buttons-impl.cpp"
//#include "examples/text-label/text-label-example.cpp"

//#include "examples/text-label-multi-language/text-label-multi-language-example.cpp"

//#include "examples/Text-Label-Emojis/Text-Label-Emojis.cpp"
//#include "examples/Text-Memory-Profiling/Text-Memory-Profiling-example.cpp"
//#include "examples/Text-Overlap/Text-Overlap-example.cpp"
//#include "examples/Text-Scrolling/Text-Scrolling-example.cpp"
//#include "examples/Textured-Mesh/Textured-Mesh-example.cpp"
//#include "examples/Tilt/Tilt-example.cpp"
//#include "examples/Tooltip/Tooltip-example.cpp"

//#include "examples/Transitions/Transition-example.cpp"
//#include "examples/Transitions/shadow-button.cpp"
//#include "examples/Transitions/shadow-button-impl.cpp"
//#include "examples/Transitions/transition-application.cpp"

//#include "examples/Visual-Transitions/Transition-example.cpp"
//#include "examples/Visual-Transitions/beat-control.cpp"
//#include "examples/Visual-Transitions/beat-control-impl.cpp"
//#include "examples/Visual-Transitions/transition-application.cpp"

